sudo: required
language: generic

branches:
    only:
        - master

services:
    - docker

before_install:
    - docker build -t di3go95/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true di3go95/docker-react npm run test

#deploy:
    #provider: elasticbeanstalk
    #region: "us-west-2"
    #app: "docker-react"
    #env: "docker-env"
    #bucket_name: ""
    #bucket_path: "docker-react" # Same as app name
    #on:
    #    branch: master
    #access_key_id: $AWS_ACCESS_KEY
    #secret_access_key: $AWS_SECRET_KEY