sudo: required
language: generic
services:
    - docker

before_install:
    - docker build -t di3go95/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true di3go95/docker-react npm run test